neo4j:
  name: neo4j-standalone
  resources:
    cpu: "1"
    memory: "3Gi"

  password: "project2phase2"

volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 2Gi

env:
  NEO4J_PLUGINS: '["graph-data-science"]'

config:
  dbms.security.procedures.unrestricted: "gds.*,apoc.*"
