# Default values for zookeeper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: confluentinc/cp-zookeeper
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "7.3.3"

service:
  type: ClusterIP
  port: 2181

resources:
   limits:
     cpu: 250m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

env:
  ZOOKEEPER_TICK_TIME: "2000"
  ZOOKEEPER_SYNC_LIMIT: "2"
