apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zookeeper.fullname" . }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "zookeeper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zookeeper.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "{{ .Values.service.port }}"
            - name: ZOOKEEPER_TICK_TIME
              value: "{{ .Values.env.ZOOKEEPER_TICK_TIME }}"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "{{ .Values.env.ZOOKEEPER_SYNC_LIMIT }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
