apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-service
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ext_port }}
      targetPort: http
      protocol: TCP
      name: kafka-ext
    - port: {{ .Values.service.int_port }}
      targetPort: http
      protocol: TCP
      name: kafka-int
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
